services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    environment:
      - PHP_EXTRA_CONFIGURE_ARGS=--with-pdo-mysql
    command: >
      sh -c "docker-php-ext-install pdo_mysql && php-fpm"

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
      - webnet

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - laravel_network

networks:
  laravel_network:
  webnet:

volumes:
  db_data:

